---
- name: Converge
  hosts: all
  diff: true
  tasks:
    - name: Set users for role
      ansible.builtin.set_fact:
        subid_users:
          - james
          - thorsten
          - svc.backup
          - systemuser123

    - name: "Include ansible_role_subuid_subgid"
      ansible.builtin.include_role:
        name: "ansible-role-subuid_subgid"
